---
- name: update ansible
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

  tasks:
    - name: install epel
      package:
        name: epel-release
        state: latest

    - name: update ansible
      package:
        name: ansible
        state: latest

